targets:
  ixtrator:ixtrator:
    builders:
      ixtrator|ixtratorGenerator:
        enabled: True

builders:
  ixtratorGenerator:
    import: 'package:ixtrator/ixtrator.dart'
    builder_factories: ['ixtratorBuilder']
    build_extensions: {".dart":  ["ixtrator.g.part"]}
    build_to: source
    auto_apply: root_package
    applies_builders: ["source_gen|combining_builder"]
    