name: ixtrator
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.0.3

# Add regular dependencies here.
dependencies:
  analyzer: ^6.2.0
  args: ^2.4.2
  build: ^2.4.1
  build_config: ^1.1.1
  source_gen: ^1.4.0
  # path: ^1.8.0
  

dev_dependencies:
  build_runner: ^2.4.6
  lints: ^2.0.0
  test: ^1.21.0



  

